# PolyWeather City Registry
# A unified "Source of Truth" for all tracked cities, coordinates, ICAO codes, and risk profiles.

CITY_REGISTRY = {
    "ankara": {
        "name": "Ankara",
        "lat": 40.1281,
        "lon": 32.9951,
        "icao": "LTAC",
        "tz_offset": 10800,
        "use_fahrenheit": False,
        "is_major": False,
        "fast_metar_refresh": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Esenboğa Airport",
        "distance_km": 24.5,
        "warning": "Inland plateau city; large diurnal swings (up to 15C+); aggressive rounding effects prominent.",
    },
    "istanbul": {
        "name": "Istanbul",
        "lat": 41.2749,
        "lon": 28.7323,
        "icao": "LTFM",
        "settlement_source": "noaa",
        "settlement_station_code": "LTFM",
        "settlement_station_label": "Istanbul Airport",
        "tz_offset": 10800,
        "use_fahrenheit": False,
        "is_major": True,
        "fast_metar_refresh": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Istanbul Airport",
        "distance_km": 34.0,
        "warning": "Market settles per NOAA LTFM whole-degree Celsius; use the day's highest whole-degree value from the weather.gov Temp column after final QC.",
    },
    "moscow": {
        "name": "Moscow",
        "lat": 55.5915,
        "lon": 37.2615,
        "icao": "UUWW",
        "settlement_source": "metar",
        "settlement_station_code": "UUWW",
        "settlement_station_label": "Vnukovo International Airport",
        "tz_offset": 10800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Vnukovo International Airport",
        "distance_km": 29.0,
        "warning": "Single UUWW METAR station; no real-time national network. Reports relatively stable between cycles but update infrequently.",
    },
    "london": {
        "name": "London",
        "lat": 51.5048,
        "lon": 0.0522,
        "icao": "EGLC",
        "tz_offset": 0,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "London City Airport",
        "distance_km": 12.7,
        "warning": "Local Thames River microclimate effects.",
    },
    "paris": {
        "name": "Paris",
        "lat": 48.9694,
        "lon": 2.4414,
        "icao": "LFPB",
        "settlement_source": "aeroweb",
        "settlement_station_code": "LFPB",
        "settlement_station_label": "Paris Le Bourget (AEROWEB)",
        "settlement_url": "https://www.wunderground.com/history/daily/fr/bonneuil-en-france/LFPB",
        "tz_offset": 3600,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Paris-Le Bourget Airport",
        "distance_km": 12.0,
        "warning": "Paris market anchors to Le Bourget METAR / LFPB history; urban heat island and low cloud north of the airport may cause bias.",
    },
    "seoul": {
        "name": "Seoul",
        "lat": 37.4602,
        "lon": 126.4407,
        "icao": "RKSI",
        "tz_offset": 32400,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "Incheon International Airport",
        "distance_km": 48.8,
        "warning": "Too far from city; large oceanic vs continental climate differences.",
    },
    "busan": {
        "name": "Busan",
        "lat": 35.1795,
        "lon": 128.9382,
        "icao": "RKPK",
        "settlement_source": "wunderground",
        "settlement_station_code": "RKPK",
        "settlement_station_label": "Busan/Gimhae International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/kr/busan/RKPK",
        "tz_offset": 32400,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Gimhae International Airport",
        "distance_km": 14.0,
        "warning": "Market settles per Wunderground Gimhae airport whole-degree Celsius; sea breeze and coastal cloud may affect the afternoon peak.",
    },
    "hong kong": {
        "name": "Hong Kong",
        "lat": 22.3019,
        "lon": 114.1742,
        "icao": "VHHH",
        "settlement_source": "hko",
        "settlement_station_code": "HKO",
        "settlement_station_label": "HK Observatory",
        "settlement_station_candidates": ["HK Observatory", "Hong Kong Observatory"],
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Hong Kong Observatory HQ",
        "distance_km": 2.0,
        "warning": "Sea breeze and terrain interact; temperature may fall quickly after afternoon convection triggers.",
    },
    "shenzhen": {
        "name": "Shenzhen",
        "lat": 22.4686,
        "lon": 113.9970,
        "icao": "LFS",
        "settlement_source": "hko",
        "settlement_station_code": "LFS",
        "settlement_station_label": "Shenzhen (HKO)",
        "settlement_station_candidates": ["Lau Fau Shan"],
        "disable_aviationweather": True,
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Shenzhen (HKO Observatory station)",
        "distance_km": 0.0,
        "warning": "Shenzhen temperature market settles per Hong Kong Observatory (HKO) station via Lau Fau Shan minute-level readings. NOT airport METAR; do not mix with Bao'an ZGSZ/VHHH reports.",
    },
    "taipei": {
        "name": "Taipei",
        "lat": 25.0377,
        "lon": 121.5149,
        "icao": "RCSS",
        "settlement_source": "cwa",
        "settlement_station_code": "466920",
        "settlement_station_label": "Taipei CWA Station",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Taipei CWA Station",
        "distance_km": 0.0,
        "warning": "Settlement per Taiwan CWA Taipei station; do not use Songshan airport METAR as the settlement source.",
    },
    "shanghai": {
        "name": "Shanghai",
        "lat": 31.1434,
        "lon": 121.8052,
        "icao": "ZSPD",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Pudong International Airport",
        "distance_km": 33.0,
        "warning": "Coastal advection plus urban heat island; afternoon high can deviate 1-2C.",
    },
    "singapore": {
        "name": "Singapore",
        "lat": 1.3644,
        "lon": 103.9915,
        "icao": "WSSS",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Changi Airport",
        "distance_km": 17.5,
        "warning": "Small year-round temperature range; mainly affected by afternoon shower timing.",
    },
    "kuala lumpur": {
        "name": "Kuala Lumpur",
        "lat": 2.7456,
        "lon": 101.7072,
        "icao": "WMKK",
        "settlement_source": "wunderground",
        "settlement_station_code": "WMKK",
        "settlement_station_label": "Kuala Lumpur International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/my/sepang-district/WMKK",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Kuala Lumpur International Airport",
        "distance_km": 45.0,
        "warning": "Market settles per Wunderground KLIA whole-degree Celsius; afternoon convection and tropical humidity shorten the peak window.",
    },
    "jakarta": {
        "name": "Jakarta",
        "lat": -6.2666,
        "lon": 106.8910,
        "icao": "WIHH",
        "settlement_source": "wunderground",
        "settlement_station_code": "WIHH",
        "settlement_station_label": "Jakarta/Halim Perdanakusuma Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/id/jakarta/WIHH",
        "tz_offset": 25200,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Halim Perdanakusuma Airport",
        "distance_km": 12.0,
        "warning": "Market settles per Wunderground Halim station whole-degree Celsius; tropical afternoon downpours can quickly depress temps around the peak.",
    },
    "manila": {
        "name": "Manila",
        "lat": 14.5086,
        "lon": 121.0198,
        "icao": "RPLL",
        "settlement_source": "wunderground",
        "settlement_station_code": "RPLL",
        "settlement_station_label": "Manila/Ninoy Aquino International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/ph/manila/RPLL",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Ninoy Aquino International Airport",
        "distance_km": 10.0,
        "warning": "Market settles per Wunderground NAIA whole-degree Celsius; sea breeze, humidity and afternoon convection compress the daily high window.",
    },
    "karachi": {
        "name": "Karachi",
        "lat": 24.9065,
        "lon": 67.1608,
        "icao": "OPKC",
        "settlement_source": "wunderground",
        "settlement_station_code": "OPKC",
        "settlement_station_label": "Karachi/Jinnah International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/pk/karachi/OPKC",
        "tz_offset": 18000,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Jinnah International Airport",
        "distance_km": 15.0,
        "min_plausible_metar_temp_c": 5.0,
        "warning": "Market settles per Wunderground Jinnah airport whole-degree Celsius; sea-breeze front, dry heat advection and haze affect peak timing.",
    },
    "tokyo": {
        "name": "Tokyo",
        "lat": 35.5523,
        "lon": 139.7798,
        "icao": "RJTT",
        "tz_offset": 32400,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Haneda Airport",
        "distance_km": 15.0,
        "warning": "Bay breeze and heat island coexist; daily high time can shift later.",
    },
    "tel aviv": {
        "name": "Tel Aviv",
        "lat": 32.0114,
        "lon": 34.8867,
        "icao": "LLBG",
        "tz_offset": 7200,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Ben Gurion Airport",
        "distance_km": 14.8,
        "warning": "Distinct sea/land breeze transition; afternoon sea breeze caps warming, peak may shift later.",
        "settlement_source": "ims",
        "settlement_station_code": "225",
        "settlement_station_label": "Lod Airport",
    },
    "toronto": {
        "name": "Toronto",
        "lat": 43.6777,
        "lon": -79.6248,
        "icao": "CYYZ",
        "tz_offset": -18000,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Pearson International Airport",
        "distance_km": 19.6,
        "warning": "Winter lake effect occasionally causes strong local cooling.",
    },
    "buenos aires": {
        "name": "Buenos Aires",
        "lat": -34.8222,
        "lon": -58.5358,
        "icao": "SAEZ",
        "tz_offset": -10800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Ezeiza International Airport",
        "distance_km": 28.1,
        "warning": "In summer the city can be 2-3C warmer than suburbs.",
    },
    "wellington": {
        "name": "Wellington",
        "lat": -41.3272,
        "lon": 174.8053,
        "icao": "NZWN",
        "tz_offset": 46800,
        "use_fahrenheit": False,
        "is_major": False,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Wellington International Airport",
        "distance_km": 5.5,
        "warning": "Strong wind affects feel but has little effect on measured temperature.",
    },
    "new york": {
        "name": "New York",
        "lat": 40.7769,
        "lon": -73.8740,
        "icao": "KLGA",
        "tz_offset": -18000,
        "use_fahrenheit": True,
        "is_major": True,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "LaGuardia Airport",
        "distance_km": 14.5,
        "warning": "East River moisture can cause temperature differences in spring.",
    },
    "los angeles": {
        "name": "Los Angeles",
        "lat": 33.9416,
        "lon": -118.4085,
        "icao": "KLAX",
        "tz_offset": -28800,
        "use_fahrenheit": True,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Los Angeles International Airport",
        "distance_km": 29.0,
        "warning": "Sea breeze and coastal stratus clearly limit afternoon warming; LAX readings often run below inland city.",
    },
    "san francisco": {
        "name": "San Francisco",
        "lat": 37.6213,
        "lon": -122.3790,
        "icao": "KSFO",
        "tz_offset": -28800,
        "use_fahrenheit": True,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "San Francisco International Airport",
        "distance_km": 20.0,
        "warning": "Bay cold air and advection fog suppress warming; SFO vs downtown gap can open quickly.",
    },
    "denver": {
        "name": "Denver",
        "display_name": "Denver",
        "lat": 39.7017,
        "lon": -104.7518,
        "icao": "KBKF",
        "tz_offset": -25200,
        "use_fahrenheit": True,
        "is_major": False,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Buckley Space Force Base",
        "distance_km": 3.5,
        "warning": "Denver plateau: solar and subsidence warming switch fast; Buckley and downtown Denver peaks often mismatch.",
    },
    "austin": {
        "name": "Austin",
        "lat": 30.1945,
        "lon": -97.6699,
        "icao": "KAUS",
        "tz_offset": -21600,
        "use_fahrenheit": True,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Austin-Bergstrom International Airport",
        "distance_km": 12.0,
        "warning": "Central Texas: afternoon mixing layer builds rapidly; dry heat and local convection widen the peak window.",
    },
    "houston": {
        "name": "Houston",
        "lat": 29.6454,
        "lon": -95.2789,
        "icao": "KHOU",
        "tz_offset": -21600,
        "use_fahrenheit": True,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "William P. Hobby Airport",
        "distance_km": 12.0,
        "warning": "Gulf moisture and sea-breeze return flow; humid conditions slow the daytime warming pace.",
    },
    "mexico city": {
        "name": "Mexico City",
        "lat": 19.4363,
        "lon": -99.0721,
        "icao": "MMMX",
        "tz_offset": -21600,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "Benito Juárez International Airport",
        "distance_km": 6.5,
        "warning": "High-altitude basin city; radiative warming and afternoon convection coexist; 1-2C deviations near the peak are common.",
    },
    "chicago": {
        "name": "Chicago",
        "lat": 41.9742,
        "lon": -87.9073,
        "icao": "KORD",
        "tz_offset": -21600,
        "use_fahrenheit": True,
        "is_major": False,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "O'Hare International Airport",
        "distance_km": 25.3,
        "warning": "Lake Michigan effect: lakeside vs inland can differ 10F+.",
    },
    "dallas": {
        "name": "Dallas",
        "lat": 32.8471,
        "lon": -96.8518,
        "icao": "KDAL",
        "tz_offset": -21600,
        "use_fahrenheit": True,
        "is_major": False,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Dallas Love Field Airport",
        "distance_km": 11.2,
        "warning": "Urban heat island makes afternoon temps slightly above suburbs in summer.",
    },
    "miami": {
        "name": "Miami",
        "lat": 25.7959,
        "lon": -80.2870,
        "icao": "KMIA",
        "tz_offset": -18000,
        "use_fahrenheit": True,
        "is_major": False,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Miami International Airport",
        "distance_km": 10.3,
        "warning": "Small temp range, stable data.",
    },
    "atlanta": {
        "name": "Atlanta",
        "lat": 33.6407,
        "lon": -84.4277,
        "icao": "KATL",
        "tz_offset": -18000,
        "use_fahrenheit": True,
        "is_major": False,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Hartsfield-Jackson Airport",
        "distance_km": 12.6,
        "warning": "Data reliable.",
    },
    "seattle": {
        "name": "Seattle",
        "lat": 47.4502,
        "lon": -122.3088,
        "icao": "KSEA",
        "tz_offset": -28800,
        "use_fahrenheit": True,
        "is_major": False,
        "risk_level": "low",
        "risk_emoji": "🟢",
        "airport_name": "Sea-Tac International Airport",
        "distance_km": 17.4,
        "warning": "Micro-climate differences exist but small.",
    },
    "lucknow": {
        "name": "Lucknow",
        "lat": 26.7606,
        "lon": 80.8893,
        "icao": "VILK",
        "tz_offset": 19800,
        "use_fahrenheit": False,
        "is_major": False,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Chaudhary Charan Singh International Airport",
        "distance_km": 14.0,
        "warning": "North India heat island; summer afternoon readings run slightly below downtown.",
    },
    "sao paulo": {
        "name": "São Paulo",
        "lat": -23.4356,
        "lon": -46.4731,
        "icao": "SBGR",
        "tz_offset": -10800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "São Paulo/Guarulhos Airport",
        "distance_km": 25.0,
        "warning": "Long distance with elevation differences; big local rain temp gaps.",
    },
    "munich": {
        "name": "Munich",
        "lat": 48.3538,
        "lon": 11.7861,
        "icao": "EDDM",
        "tz_offset": 3600,
        "use_fahrenheit": False,
        "is_major": False,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "Munich Airport",
        "distance_km": 28.5,
        "warning": "Very far; open airport cools fast at night; winter fog caps the temperature.",
    },
    "milan": {
        "name": "Milan",
        "lat": 45.6306,
        "lon": 8.7281,
        "icao": "LIMC",
        "settlement_source": "metar",
        "tz_offset": 3600,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Malpensa Airport",
        "distance_km": 49.0,
        "warning": "Far from downtown; peak and night-cooling pace should follow the airport station.",
    },
    "warsaw": {
        "name": "Warsaw",
        "lat": 52.1657,
        "lon": 20.9671,
        "icao": "EPWA",
        "settlement_source": "metar",
        "tz_offset": 3600,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Chopin Airport",
        "distance_km": 10.0,
        "warning": "Plains terrain: radiative cooling significant; morning and night drops may be fast.",
    },
    "helsinki": {
        "name": "Helsinki",
        "lat": 60.3172,
        "lon": 24.9633,
        "icao": "EFHK",
        "settlement_source": "wunderground",
        "settlement_station_code": "EFHK",
        "settlement_station_label": "Helsinki Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/fi/vantaa/EFHK",
        "tz_offset": 7200,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Helsinki Airport",
        "distance_km": 17.0,
        "warning": "Market settles per Wunderground Helsinki airport whole-degree Celsius; high-latitude sunlight changes fast and cold advection hits the daily peak.",
    },
    "amsterdam": {
        "name": "Amsterdam",
        "lat": 52.3086,
        "lon": 4.7639,
        "icao": "EHAM",
        "settlement_source": "wunderground",
        "settlement_station_code": "EHAM",
        "settlement_station_label": "Amsterdam Airport Schiphol Station",
        "settlement_url": "https://www.wunderground.com/history/daily/nl/schiphol/EHAM",
        "tz_offset": 3600,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Amsterdam Schiphol Airport",
        "distance_km": 17.0,
        "warning": "Market settles per Wunderground Schiphol station whole-degree Celsius; North Sea breeze and frontal cloud cap afternoon warming.",
    },
    "madrid": {
        "name": "Madrid",
        "lat": 40.4722,
        "lon": -3.5608,
        "icao": "LEMD",
        "settlement_source": "metar",
        "tz_offset": 3600,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Adolfo Suárez Madrid-Barajas",
        "distance_km": 13.0,
        "warning": "Airport NE of the city in open terrain; apparent temperature can deviate from downtown when the mixing layer strengthens.",
    },

    "chengdu": {
        "name": "Chengdu",
        "lat": 30.5785,
        "lon": 103.9471,
        "icao": "ZUUU",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Chengdu Shuangliu International Airport",
        "distance_km": 16.0,
        "warning": "Basin terrain; slow night cooling, cloud and fog modulate daytime warming.",
    },
    "chongqing": {
        "name": "Chongqing",
        "lat": 29.7196,
        "lon": 106.6416,
        "icao": "ZUCK",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "Chongqing Jiangbei International Airport",
        "distance_km": 19.0,
        "warning": "One of the four hot-weather cities; long hot humid summers with warm nights.",
    },
    "guangzhou": {
        "name": "Guangzhou",
        "lat": 23.3924,
        "lon": 113.2988,
        "icao": "ZGGG",
        "settlement_source": "wunderground",
        "settlement_station_code": "ZGGG",
        "settlement_station_label": "Guangzhou Baiyun International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/cn/guangzhou/ZGGG",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Guangzhou Baiyun International Airport",
        "distance_km": 28.0,
        "warning": "Market settles per Wunderground Guangzhou Baiyun airport whole-degree Celsius; Pearl Delta winds and afternoon convection swing peak timing.",
    },
    "qingdao": {
        "name": "Qingdao",
        "lat": 36.3620,
        "lon": 120.0882,
        "icao": "ZSQD",
        "settlement_source": "wunderground",
        "settlement_station_code": "ZSQD",
        "settlement_station_label": "Qingdao Jiaodong International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/cn/qingdao/ZSQD",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Qingdao Jiaodong International Airport",
        "distance_km": 39.0,
        "warning": "Market settles per Wunderground Qingdao Jiaodong airport whole-degree Celsius; coastal breeze, low cloud and sea fog affect warming efficiency.",
    },
    "beijing": {
        "name": "Beijing",
        "lat": 40.0801,
        "lon": 116.5846,
        "icao": "ZBAA",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Beijing Capital International Airport",
        "distance_km": 25.0,
        "warning": "North interior: hot dry summers, cold winters, sandy/spring storms common.",
    },
    "wuhan": {
        "name": "Wuhan",
        "lat": 30.7838,
        "lon": 114.2081,
        "icao": "ZHHH",
        "tz_offset": 28800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "high",
        "risk_emoji": "🔴",
        "airport_name": "Wuhan Tianhe International Airport",
        "distance_km": 26.0,
        "warning": "Jianghan plain: humid, with long sultry spells in summer.",
    },
    "panama city": {
        "name": "Panama City",
        "lat": 8.9733,
        "lon": -79.5556,
        "icao": "MPMG",
        "settlement_source": "wunderground",
        "settlement_station_code": "MPMG",
        "settlement_station_label": "Panama City/Marcos A. Gelabert Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/pa/panama-city/MPMG",
        "tz_offset": -18000,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Marcos A. Gelabert Airport",
        "distance_km": 6.0,
        "warning": "Market settles per Wunderground Marcos A. Gelabert station whole-degree Celsius; tropical convection often truncates the afternoon peak.",
    },
    "cape town": {
        "name": "Cape Town",
        "lat": -33.9696,
        "lon": 18.5972,
        "icao": "FACT",
        "settlement_source": "wunderground",
        "settlement_station_code": "FACT",
        "settlement_station_label": "Cape Town International Airport Station",
        "settlement_url": "https://www.wunderground.com/history/daily/za/matroosfontein/FACT",
        "tz_offset": 7200,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "Cape Town International Airport",
        "distance_km": 20.0,
        "warning": "Market settles per Wunderground Cape Town airport whole-degree Celsius; sea breeze and advected cloud control the afternoon warming pace.",
    },
    "jeddah": {
        "name": "Jeddah",
        "lat": 21.6702,
        "lon": 39.1525,
        "icao": "OEJN",
        "settlement_source": "ncm",
        "settlement_station_code": "OEJN",
        "settlement_station_label": "Jeddah King Abdulaziz Intl (NCM)",
        "settlement_url": "https://www.wunderground.com/history/daily/sa/jeddah/OEJN",
        "tz_offset": 10800,
        "use_fahrenheit": False,
        "is_major": True,
        "risk_level": "medium",
        "risk_emoji": "🟡",
        "airport_name": "King Abdulaziz International Airport",
        "distance_km": 18.0,
        "warning": "Market settles per Wunderground Jeddah King Abdulaziz airport whole-degree Celsius; sea breeze and dust transport shift peak timing in dry heat.",
    },
}

ALIASES = {
    # English shortcuts
    "ank": "ankara", "ist": "istanbul", "ltfm": "istanbul", "mos": "moscow", "mow": "moscow", "uuww": "moscow", "vnukovo": "moscow", "lon": "london", "par": "paris",
    "nyc": "new york", "ny": "new york", "chi": "chicago", 
    "la": "los angeles", "lax": "los angeles", "losangeles": "los angeles",
    "sf": "san francisco", "sfo": "san francisco", "sanfrancisco": "san francisco",
    "aur": "denver", "denver": "denver", "buckley": "denver", "kbkf": "denver", "aurora": "denver",
    "aus": "austin", "kaus": "austin",
    "hou": "houston", "khou": "houston", "hobby": "houston",
    "cdmx": "mexico city", "mexicocity": "mexico city", "mmmx": "mexico city",
    "dal": "dallas", "mia": "miami", "atl": "atlanta", 
    "sea": "seattle", "tor": "toronto", "sel": "seoul", 
    "seo": "seoul", "hkg": "hong kong", "hk": "hong kong",
    "lfs": "shenzhen", "laufaushan": "shenzhen", "lau fau shan": "shenzhen",
    "tpe": "taipei", "tp": "taipei", "taipei": "taipei",
    "pus": "busan", "bus": "busan", "rkpk": "busan",
    "sha": "shanghai", "sh": "shanghai", "sin": "singapore",
    "sg": "singapore", "tok": "tokyo", "tyo": "tokyo",
    "kul": "kuala lumpur", "wmkk": "kuala lumpur", "sepang": "kuala lumpur",
    "jkt": "jakarta", "wihh": "jakarta", "halim": "jakarta",
    "mnl": "manila", "manila": "manila", "rpll": "manila",
    "khi": "karachi", "karachi": "karachi", "opkc": "karachi", "jinnah": "karachi",
    "hel": "helsinki", "efhk": "helsinki", "vantaa": "helsinki",
    "ams": "amsterdam", "eham": "amsterdam", "schiphol": "amsterdam",
    "pty": "panama city", "mpmg": "panama city", "panamacity": "panama city",
    "cpt": "cape town", "fact": "cape town", "capetown": "cape town", "matroosfontein": "cape town",
    "jed": "jeddah", "oejn": "jeddah",
    "tlv": "tel aviv", "telaviv": "tel aviv",
    "ba": "buenos aires", "wel": "wellington",
    "luc": "lucknow", "sp": "sao paulo", "mun": "munich",
    "mil": "milan", "mxp": "milan", "waw": "warsaw", "war": "warsaw",
    "mad": "madrid", "madrid": "madrid", "lemd": "madrid",
    
    # Chinese names
    "ctu": "chengdu", "cd": "chengdu",
    "ckg": "chongqing", "cq": "chongqing",
    "szx": "shenzhen", "sz": "shenzhen",
    "can": "guangzhou", "gz": "guangzhou", "zggg": "guangzhou",
    "tao": "qingdao", "qdo": "qingdao", "qingdao": "qingdao", "zsqd": "qingdao",
    "pek": "beijing", "bjs": "beijing", "bj": "beijing",
    "wuh": "wuhan", "wh": "wuhan",
}
