"""Optional LLM integration layer for unstructured weather analysis.

Disabled by default. When configured with a Google AI Studio API key
(``GEMINI_API_KEY`` or ``GOOGLE_API_KEY``), provides LLM-powered
analysis of unstructured weather data (TAF reports, observation
narratives) that the structured DEB pipeline doesn't naturally handle.

Design principles:
- **Never in the critical path.** All core decisions (forecast gap,
  probability, position sizing) are purely mathematical.
- **No-op when disabled.** Every method returns ``None`` immediately
  if the API key is not set. No errors, no retries.
- **Asynchronous.** Uses the project's shared httpx client.
- **Cheap model by default.** Gemma 4 26B MoE (~$0.13/M input tokens)
  is the default. Claude is not used.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Optional

from src.async_infra.http_client import get_shared_client

logger = logging.getLogger(__name__)

# Default model — cheapest capable option
_DEFAULT_MODEL = "gemma-4-26b-a4b-it"
_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"


@dataclass
class TAFAnalysisResult:
    """Structured output from LLM-based TAF analysis."""

    disruption_level: str  # "none", "low", "medium", "high"
    cloud_cap_temp_c: Optional[float] = None
    wind_disruption: bool = False
    precipitation_timing: list[str] = field(default_factory=list)
    summary: str = ""
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass
class TradeNarrative:
    """Human-readable trade rationale generated by the LLM."""

    headline: str
    reasoning: str
    risks: list[str] = field(default_factory=list)
    raw: dict[str, Any] = field(default_factory=dict)


class LLMGapClient:
    """Optional LLM layer for unstructured weather data analysis.

    Usage:
        client = LLMGapClient()  # disabled — all methods return None
        # or:
        client = LLMGapClient(api_key="AI...")  # enabled

        result = await client.analyze_taf(taf_text)
        narrative = await client.generate_trade_narrative(analysis, signal)
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = _DEFAULT_MODEL,
    ) -> None:
        """
        Args:
            api_key: Google AI Studio API key. If ``None``, reads from
                ``GEMINI_API_KEY`` then ``GOOGLE_API_KEY`` env vars.
                If neither is set, the client is **disabled**.
            model: Model name to use. Default is Gemma 4 26B MoE.
        """
        self._api_key = api_key or os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY") or ""
        self._model = model
        self._disabled = not self._api_key
        self._shared = get_shared_client()

        if self._disabled:
            logger.info("LLMGapClient disabled — no API key configured")
        else:
            logger.info(
                "LLMGapClient enabled (model=%s, key=%s...%s)",
                model,
                self._api_key[:6],
                self._api_key[-4:],
            )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def analyze_taf(self, taf_text: str, city: str = "") -> Optional[TAFAnalysisResult]:
        """Analyse a raw TAF report for temperature disruption signals.

        Parses unstructured TAF text for:
        - Cloud cover that could cap the afternoon peak
        - Wind shear / turbulence that might affect mixing
        - Precipitation timing relative to peak window
        - Overall disruption level

        Args:
            taf_text: Raw TAF report string.
            city: City name for context (optional).

        Returns:
            ``TAFAnalysisResult`` if enabled, ``None`` if disabled.
        """
        if self._disabled or not taf_text:
            return None

        prompt = (
            f"Analyse this TAF for {city or 'the city'} and return JSON "
            "with exactly these keys:\n"
            "- disruption_level: one of \"none\", \"low\", \"medium\", \"high\"\n"
            "- cloud_cap_temp_c: estimated temperature cap from clouds (float or null)\n"
            "- wind_disruption: true if wind shear/turbulence would affect peak mixing\n"
            "- precipitation_timing: list of time windows with precipitation\n"
            "- summary: one-sentence explanation\n\n"
            f"TAF: {taf_text}"
        )

        raw = await self._call_llm(prompt)
        if not raw:
            return None
        return self._parse_taf(raw)

    async def generate_trade_narrative(
        self,
        analysis_result: dict[str, Any],
        signal_info: dict[str, Any],
    ) -> Optional[TradeNarrative]:
        """Generate a human-readable trade rationale.

        Creates an explanation of why a trade signal was generated —
        useful for Telegram notifications and the ops dashboard.

        Args:
            analysis_result: City analysis dict from the pipeline.
            signal_info: Signal details (direction, gap, price, etc.).

        Returns:
            ``TradeNarrative`` if enabled, ``None`` if disabled.
        """
        if self._disabled:
            return None

        city = analysis_result.get("city", "Unknown")
        prob = analysis_result.get("probability", 0)
        gap = signal_info.get("gap", 0)
        price = signal_info.get("market_price", 0)
        direction = signal_info.get("direction", "BUY")

        prompt = (
            f"We are trading weather prediction markets. "
            f"{city}: model probability={prob:.1f}%, market price={price:.2%}, "
            f"gap={gap:.1%} ({direction}). "
            "Explain the rationale for this trade in 2-3 sentences. "
            "Return JSON with keys: headline (short), reasoning (2-3 sentences), "
            "risks (list of 1-3 risk factors)."
        )

        raw = await self._call_llm(prompt)
        if not raw:
            return None
        return self._parse_narrative(raw)

    async def augment_analysis(
        self,
        analysis_result: dict[str, Any],
        weather_data: dict[str, Any],
    ) -> Optional[dict[str, Any]]:
        """Optionally augment the structured analysis with LLM insights.

        Returns a dict with additional interpretation fields, or ``None``
        if disabled. The core gap strategy does **not** use this —
        it's purely informational for dashboards and Telegram messages.

        Args:
            analysis_result: City analysis dict.
            weather_data: Raw weather data (observations, forecasts).

        Returns:
            Augmented insights dict, or ``None`` if disabled.
        """
        if self._disabled:
            return None

        city = analysis_result.get("city", "Unknown")
        temp = weather_data.get("temperature_c", "N/A")
        condition = weather_data.get("condition_text", "")

        prompt = (
            f"Given current weather in {city}: temperature={temp}°C, "
            f"condition={condition}. "
            "What is the key factor that will determine if today's high "
            f"exceeds the forecast? Return JSON with key: 'key_factor' (string)."
        )

        return await self._call_llm(prompt)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _call_llm(self, prompt: str) -> Optional[dict[str, Any]]:
        """Call the Gemma 4 API via Google AI Studio REST endpoint.

        Returns parsed JSON or ``None`` on failure.
        """
        url = f"{_API_BASE}/{self._model}:generateContent"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": 0.3,
                "maxOutputTokens": 512,
            },
        }

        try:
            resp = await self._shared.post(
                url,
                params={"key": self._api_key},
                json=payload,
                headers={"Content-Type": "application/json"},
            )
            if resp.status_code != 200:
                logger.warning("LLM API error %d: %s", resp.status_code, resp.text[:200])
                return None

            data = resp.json()
            text = (
                data.get("candidates", [{}])[0]
                .get("content", {})
                .get("parts", [{}])[0]
                .get("text", "")
            )
            if not text:
                return None

            cleaned = text.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[-1]
                cleaned = cleaned.rsplit("```", 1)[0]
            return json.loads(cleaned)

        except Exception as exc:
            logger.debug("LLM API call failed: %s", exc)
            return None

    def _parse_taf(self, raw: dict[str, Any]) -> TAFAnalysisResult:
        return TAFAnalysisResult(
            disruption_level=raw.get("disruption_level", "none"),
            cloud_cap_temp_c=raw.get("cloud_cap_temp_c"),
            wind_disruption=bool(raw.get("wind_disruption", False)),
            precipitation_timing=raw.get("precipitation_timing", []),
            summary=raw.get("summary", ""),
            raw=raw,
        )

    def _parse_narrative(self, raw: dict[str, Any]) -> TradeNarrative:
        return TradeNarrative(
            headline=raw.get("headline", ""),
            reasoning=raw.get("reasoning", ""),
            risks=raw.get("risks", []),
            raw=raw,
        )
